### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by waknauss** [AlainDessi/AdMagicTools#3]
Hi, 
I was wondering if I could have your permission to link this project to "Awesome Unipaas": https://github.com/leverage-latitude/awesome-unipaas

**Comment by AlainDessi** [comment]
Hi,
Yes of course you can ! thanks !
  <http://www.alain-dessi.com>
tél. : *06 14 03 48 55*
email : alain.dessi@gmail.com
web : www.alain-dessi.com
linkdin <https://fr.linkedin.com/in/alaindessi> - twitter
<http://twitter.com/AlainDessi> - google+ <http://goog.la/AlainDessi>

**Comment by waknauss** [comment]
It has been added!
